### PR TITLE
Added support for TypeScript

### PR DESCRIPTION
**Pull request by jantimon**
Hi

we use this tiny but powerful library in a typescript project and would love to merge back our typings:

index.d.ts
```js
export default function (image: string | HTMLImageElement): Promise<HTMLImageElement>;
export default function (images: string[] | HTMLImageElement[]): Promise<HTMLImageElement[]>;
```

It says that it accepts either a `string` or a `HTMLImageElement` and returns a `Promise` which resolves to a `HTMLImageElement`.

The method definition is overloaded - so if it is called with an array typescript will know that the result is also an array.

Usage in typescript (with this pr) would be quite easy (exactly like es2015):

```js
import loadImage from 'image-promise';
loadImage('some/url').then((result) => console.log(result));
```

The main javascript code would not be affected so people without typescript won't notice anything.

### CODE REVIEW

**Comment by bfred-it** [comment]
Sounds good, thanks!

Does this actually work given that NodeJS will actually read the common.js file and not the index.js?

Also does that allow any type of iterable like NodeList and jQuery objects?

**Comment by bfred-it** [comment]
While you're at it, do you mind trying version `5.0.0-0`? I cleaned it up a bit. You can install it with: `npm install object-fit-images@next`

**Comment by jantimon** [comment]
Is https://github.com/bfred-it/image-promise/blob/e68a54c3b8c6cc9e1e1e6ef0cfa1b7021d10079b/index.js#L48 obsolete?

**Comment by bfred-it** [comment]
Right

**Comment by jantimon** [comment]
I really like the cleaned up version.

I just mixed up L48 with https://gist.github.com/paulirish/268257#file-gistfile1-js-L15

What's the browser support for 5.0?

**Comment by bfred-it** [comment]
Same as before: Edge 12+ because of `Promise`, but once that's polyfilled, it should be IE9+ (untested). IE9 is the first one supporting `[].map` and `el.addEventListener`

That line is no longer needed because the cache is gone and therefore I no longer need to handle GC

**Comment by bfred-it** [comment]
I'm ready to merge if you confirm https://github.com/bfred-it/image-promise/pull/2#issuecomment-282790770

**Comment by jantimon** [comment]
It would show a type error if you would pass a DivElement, a jQuery Element or a NodeList because this could cause a runtime error. However we could change this.

NodeJS will always look for `main` so this would be no problem

**Comment by bfred-it** [comment]
No, a jQuery element, a NodeList and any iterable that has a `.length` property works fine.

In 4051fb0075b7c2b858033a9385c323a705aa571b I just added extra checks for everything else (non-`img` tags and null values) to avoid runtime errors

**Comment by bfred-it** [comment]
Do you mind resubmitting this?

**Pull request closed without merging**
